markdown: rdiscount
permalink: /4LTLS/posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Top-Law-Schools 4Ls
url: http://4lofaride.com
description: A place where 4ls can be 4ls.
twitter: top-law-schools4ls
